# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .connection import *
from .dag import *
from .pool import *
from .provider import *
from .role import *
from .user import *
from .variable import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_airflow.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_airflow.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "airflow",
  "mod": "index/connection",
  "fqn": "pulumi_airflow",
  "classes": {
   "airflow:index/connection:Connection": "Connection"
  }
 },
 {
  "pkg": "airflow",
  "mod": "index/dag",
  "fqn": "pulumi_airflow",
  "classes": {
   "airflow:index/dag:Dag": "Dag"
  }
 },
 {
  "pkg": "airflow",
  "mod": "index/pool",
  "fqn": "pulumi_airflow",
  "classes": {
   "airflow:index/pool:Pool": "Pool"
  }
 },
 {
  "pkg": "airflow",
  "mod": "index/role",
  "fqn": "pulumi_airflow",
  "classes": {
   "airflow:index/role:Role": "Role"
  }
 },
 {
  "pkg": "airflow",
  "mod": "index/user",
  "fqn": "pulumi_airflow",
  "classes": {
   "airflow:index/user:User": "User"
  }
 },
 {
  "pkg": "airflow",
  "mod": "index/variable",
  "fqn": "pulumi_airflow",
  "classes": {
   "airflow:index/variable:Variable": "Variable"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "airflow",
  "token": "pulumi:providers:airflow",
  "fqn": "pulumi_airflow",
  "class": "Provider"
 }
]
"""
)
