# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'RoleAction',
]

@pulumi.output_type
class RoleAction(dict):
    def __init__(__self__, *,
                 action: str,
                 resource: str):
        """
        :param str action: The name of the permission.
        :param str resource: The name of the resource.
        """
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "resource", resource)

    @property
    @pulumi.getter
    def action(self) -> str:
        """
        The name of the permission.
        """
        return pulumi.get(self, "action")

    @property
    @pulumi.getter
    def resource(self) -> str:
        """
        The name of the resource.
        """
        return pulumi.get(self, "resource")


