// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Pulumi.Airflow
{
    public static class Config
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly Pulumi.Config __config = new Pulumi.Config("airflow");

        private static readonly __Value<string?> _baseEndpoint = new __Value<string?>(() => __config.Get("baseEndpoint"));
        public static string? BaseEndpoint
        {
            get => _baseEndpoint.Get();
            set => _baseEndpoint.Set(value);
        }

        private static readonly __Value<string?> _oauth2Token = new __Value<string?>(() => __config.Get("oauth2Token"));
        /// <summary>
        /// The oauth to use for API authentication
        /// </summary>
        public static string? Oauth2Token
        {
            get => _oauth2Token.Get();
            set => _oauth2Token.Set(value);
        }

        private static readonly __Value<string?> _password = new __Value<string?>(() => __config.Get("password"));
        /// <summary>
        /// The password to use for API basic authentication
        /// </summary>
        public static string? Password
        {
            get => _password.Get();
            set => _password.Set(value);
        }

        private static readonly __Value<string?> _username = new __Value<string?>(() => __config.Get("username"));
        /// <summary>
        /// The username to use for API basic authentication
        /// </summary>
        public static string? Username
        {
            get => _username.Get();
            set => _username.Set(value);
        }

    }
}
