// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func GetBaseEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "airflow:baseEndpoint")
}

// The oauth to use for API authentication
func GetOauth2Token(ctx *pulumi.Context) string {
	return config.Get(ctx, "airflow:oauth2Token")
}

// The password to use for API basic authentication
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "airflow:password")
}

// The username to use for API basic authentication
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "airflow:username")
}
