// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func GetBaseEndpoint(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "airflow:baseEndpoint")
	if err == nil {
		return v
	}
	var value string
	if d := getEnvOrDefault(nil, nil, "AIRFLOW_BASE_ENDPOINT"); d != nil {
		value = d.(string)
	}
	return value
}

// Disable SSL verification
func GetDisableSslVerification(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "airflow:disableSslVerification")
}

// The oauth to use for API authentication
func GetOauth2Token(ctx *pulumi.Context) string {
	return config.Get(ctx, "airflow:oauth2Token")
}

// The password to use for API basic authentication
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "airflow:password")
}

// The username to use for API basic authentication
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "airflow:username")
}
