# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

baseEndpoint: Optional[str]

oauth2Token: Optional[str]
"""
The oauth to use for API authentication
"""

password: Optional[str]
"""
The password to use for API basic authentication
"""

username: Optional[str]
"""
The username to use for API basic authentication
"""

