// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airflow

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the airflow package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	BaseEndpoint pulumi.StringOutput `pulumi:"baseEndpoint"`
	// The oauth to use for API authentication
	Oauth2Token pulumi.StringPtrOutput `pulumi:"oauth2Token"`
	// The password to use for API basic authentication
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// The username to use for API basic authentication
	Username pulumi.StringPtrOutput `pulumi:"username"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.BaseEndpoint == nil {
		return nil, errors.New("invalid value for required argument 'BaseEndpoint'")
	}
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:airflow", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	BaseEndpoint string `pulumi:"baseEndpoint"`
	// Disable SSL verification
	DisableSslVerification *bool `pulumi:"disableSslVerification"`
	// The oauth to use for API authentication
	Oauth2Token *string `pulumi:"oauth2Token"`
	// The password to use for API basic authentication
	Password *string `pulumi:"password"`
	// The username to use for API basic authentication
	Username *string `pulumi:"username"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	BaseEndpoint pulumi.StringInput
	// Disable SSL verification
	DisableSslVerification pulumi.BoolPtrInput
	// The oauth to use for API authentication
	Oauth2Token pulumi.StringPtrInput
	// The password to use for API basic authentication
	Password pulumi.StringPtrInput
	// The username to use for API basic authentication
	Username pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

func (o ProviderOutput) BaseEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.BaseEndpoint }).(pulumi.StringOutput)
}

// The oauth to use for API authentication
func (o ProviderOutput) Oauth2Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Oauth2Token }).(pulumi.StringPtrOutput)
}

// The password to use for API basic authentication
func (o ProviderOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

// The username to use for API basic authentication
func (o ProviderOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Username }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
