// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./connection";
export * from "./dag";
export * from "./pool";
export * from "./provider";
export * from "./role";
export * from "./user";
export * from "./variable";

// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

// Import resources to register:
import { Connection } from "./connection";
import { Dag } from "./dag";
import { Pool } from "./pool";
import { Role } from "./role";
import { User } from "./user";
import { Variable } from "./variable";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "airflow:index/connection:Connection":
                return new Connection(name, <any>undefined, { urn })
            case "airflow:index/dag:Dag":
                return new Dag(name, <any>undefined, { urn })
            case "airflow:index/pool:Pool":
                return new Pool(name, <any>undefined, { urn })
            case "airflow:index/role:Role":
                return new Role(name, <any>undefined, { urn })
            case "airflow:index/user:User":
                return new User(name, <any>undefined, { urn })
            case "airflow:index/variable:Variable":
                return new Variable(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("airflow", "index/connection", _module)
pulumi.runtime.registerResourceModule("airflow", "index/dag", _module)
pulumi.runtime.registerResourceModule("airflow", "index/pool", _module)
pulumi.runtime.registerResourceModule("airflow", "index/role", _module)
pulumi.runtime.registerResourceModule("airflow", "index/user", _module)
pulumi.runtime.registerResourceModule("airflow", "index/variable", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("airflow", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:airflow") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
